"""
Extract transactions from the BTW Excel and emit a SQL file with INSERT
statements you can paste into the Supabase SQL editor.

Usage:
    python3 scripts/extract_excel.py <path-to-xlsx> > supabase/data.sql
"""
from __future__ import annotations

import re
import sys
from datetime import datetime
from openpyxl import load_workbook

SHEET_LOCATION_MAP = {
    "BOSHUT - 2024":          "Boshut",
    "BOSHUT - 2025":          "Boshut",
    "BOSHUT - 2026":          "Boshut",
    "AUF DER PLATTE - 2025":  "Auf der Platte",
    "AUF DER PLATTE - 2026":  "Auf der Platte",
    "PRIVE - 2025":           "Privé",
}

# Normalize the BTW labels found in the source data to the canonical ones
# we seeded in supabase/schema.sql.
BTW_LABEL_MAP = {
    "hoog (21%) - inkoop":   "Hoog (21%) - inkoop",
    "hoog (21%) - verkoop":  "Hoog (21%) - verkoop",
    "hoog - inkoop (19%)":   "Hoog - inkoop (19%)",
    "hoog - verkoop (19%)":  "Hoog - verkoop (19%)",
    "laag - inkoop (9%)":    "Laag - inkoop (9%)",
    "laag - inkoop (6%)":    "Laag - inkoop (6%)",
    "laag - verkoop (9%)":   "Laag - verkoop (9%)",
    "laag-verkoop (9%)":     "Laag - verkoop (9%)",
    "laag-verkoop  (9%)":    "Laag - verkoop (9%)",
    "verlegd (0%)":          "Verlegd (0%)",
}


def sql_str(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_num(n) -> str:
    if n is None or n == "":
        return "0"
    try:
        return f"{float(n):.2f}"
    except (TypeError, ValueError):
        return "0"


def parse_ledger_code(raw: str | None) -> str | None:
    """'1010 huisvestingkosten' → '1010'; '8000 - huurinkomsten' → '8000'."""
    if not raw:
        return None
    s = str(raw).strip()
    # First non-empty token, stripped of trailing punctuation
    m = re.match(r"\s*(\d+)", s)
    return m.group(1) if m else None


def normalize_btw(raw: str | None) -> str | None:
    if not raw:
        return None
    key = re.sub(r"\s+", " ", str(raw).strip().lower())
    return BTW_LABEL_MAP.get(key) or BTW_LABEL_MAP.get(key.replace(" ", "")) or None


def coerce_date(v) -> datetime | None:
    if isinstance(v, datetime):
        return v
    if isinstance(v, str):
        for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y"):
            try:
                return datetime.strptime(v, fmt)
            except ValueError:
                continue
    return None


def coerce_int(v) -> int | None:
    if v is None or v == "":
        return None
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


def coerce_float(v) -> float | None:
    if v is None or v == "":
        return None
    if isinstance(v, str):
        v = v.replace(",", ".").strip()
        if not re.match(r"^-?\d+(\.\d+)?$", v):
            return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: extract_excel.py <path-to-xlsx>", file=sys.stderr)
        sys.exit(1)

    wb = load_workbook(sys.argv[1], data_only=True)
    rows_emitted = 0
    skipped = []

    out = sys.stdout
    print("-- Auto-generated by scripts/extract_excel.py", file=out)
    print("-- Run AFTER schema.sql.", file=out)
    print("", file=out)
    print("begin;", file=out)

    for sheet_name, location_name in SHEET_LOCATION_MAP.items():
        if sheet_name not in wb.sheetnames:
            print(f"-- skipping {sheet_name}: not in workbook", file=out)
            continue
        ws = wb[sheet_name]
        print(f"-- ==== {sheet_name} → {location_name} ====", file=out)
        for raw_row in ws.iter_rows(min_row=11, values_only=True):
            # Expected columns: A=Boekstuk B=Datum C=Aangifteperiode
            # D=Bedrag in E=BTW in F=Bedrag uit G=BTW uit H=BTW code
            # I=Grootboek J=Omschrijving
            if not raw_row or len(raw_row) < 10:
                continue
            boekstuk = coerce_int(raw_row[0])
            datum    = coerce_date(raw_row[1])
            if datum is None:
                # No date → skip empty/placeholder rows
                continue

            bedrag_in = coerce_float(raw_row[3]) or 0.0
            btw_in    = coerce_float(raw_row[4]) or 0.0
            bedrag_uit = coerce_float(raw_row[5]) or 0.0
            btw_uit    = coerce_float(raw_row[6]) or 0.0

            btw_label  = normalize_btw(raw_row[7])
            ledger_code = parse_ledger_code(raw_row[8])
            omschrijving = raw_row[9] if raw_row[9] is not None else None
            if isinstance(omschrijving, str):
                omschrijving = omschrijving.strip()

            if btw_label is None and raw_row[7]:
                skipped.append(f"  [{sheet_name} row boekstuk={boekstuk}] unknown BTW '{raw_row[7]}'")

            sql = (
                "insert into public.transactions ("
                "location_id,boekstuk,datum,"
                "bedrag_inkomsten,btw_inkomsten,bedrag_uitgaven,btw_uitgaven,"
                "btw_code_id,ledger_account_id,omschrijving"
                ") values ("
                f"(select id from public.locations where name = {sql_str(location_name)}),"
                f"{boekstuk if boekstuk is not None else 'NULL'},"
                f"DATE '{datum.strftime('%Y-%m-%d')}',"
                f"{sql_num(bedrag_in)},{sql_num(btw_in)},"
                f"{sql_num(bedrag_uit)},{sql_num(btw_uit)},"
                f"{'(select id from public.btw_codes where label = ' + sql_str(btw_label) + ')' if btw_label else 'NULL'},"
                f"{'(select id from public.ledger_accounts where code = ' + sql_str(ledger_code) + ')' if ledger_code else 'NULL'},"
                f"{sql_str(omschrijving)}"
                ");"
            )
            print(sql, file=out)
            rows_emitted += 1

    print("commit;", file=out)
    print("", file=out)
    print(f"-- Total rows: {rows_emitted}", file=out)
    if skipped:
        print("-- Warnings:", file=out)
        for w in skipped:
            print("-- " + w, file=out)

    print(f"Emitted {rows_emitted} INSERT rows; {len(skipped)} warnings", file=sys.stderr)


if __name__ == "__main__":
    main()
